# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93c88d636ba4d0074b7c248398eb5f9d965bc2008c40d95f0fc21c549d49f1e47009d9b70ad8246e5fbf0737e823ee69cd7589b7490f9c5f904d269bd51d0f79

test:
  secret_key_base: be22caaf229ba21550ee3607bbb8bc570878093dcacf832bf3e4965ac5fbe5e4e6843d6c9c353d17cb36769fbe2dd116e3edc681199b39758d1ab0eed8a4cc42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
